[package]
name = "ageing"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.64"

[dev-dependencies]
criterion = "0.5.1"
rand = "0.8.5"
priority-queue = "2.1.1"

[[bench]]
name = "timing"
harness = false

